server:
  host: 127.0.0.1
  port: 3000

# Path to secrets file (can be relative or absolute)
secrets_file: secrets/ci.yaml

# Path to node sockets
node_sockets:
  tag: Local
  contents:
    node_to_client_socket: preprod.socket
    tracer_socket: preprod_tracer.socket

# Path to Cardano protocol config file
protocol_config_path: config/preprod/config.json

database:
  host: localhost
  port: 5432
  database_name: hoard_test
  pool:
    size: 5
    acquisition_timeout_seconds: 5
    aging_timeout_seconds: 600
    idleness_timeout_seconds: 300

logging:
  minimum_severity: DEBUG

# Maximum number of file descriptors
max_file_descriptors: 16384

# Cooldown period after a peer failure before retrying (in seconds)
peer_failure_cooldown_seconds: 300
